[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ANON"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "gooey>=1.0.8.1",
    "ocrmypdf>=17.10.0",
    "pymupdf>=1.28.2",
    "pytesseract>=0.3.13",
    "six>=1.17.0",
    "ruff>=0.15.22",
    "tesseract>=0.1.3",
]

[project.scripts]
create-pipeline = "Shared_Functions.Pipeline_Functions.pipeline_generator:main"
clear-pipeline = "Shared_Functions.Pipeline_Functions.wipe_pipeline_data:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["Shared_Functions*"]
