[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ANON"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
create-pipeline = "Shared_Functions.Pipeline_Functions.pipeline_generator:main"
clear-pipeline = "Shared_Functions.Pipeline_Functions.wipe_pipeline_data:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["Shared_Functions*"]
