name: Build app

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        run: python -m pip install uv

      - name: Check uv version
        run: uv --version

      - name: Sync project dependencies
        run: uv sync --frozen
      
      - name: Install Tesseract
        run: >
          winget install
          --exact
          --id UB-Mannheim.TesseractOCR
          --silent
          --accept-package-agreements
          --accept-source-agreements

      - name: Download Danish Tesseract language data
        shell: powershell
        run: |
          $tessdata = "C:\Program Files\Tesseract-OCR\tessdata"

          Invoke-WebRequest `
          -Uri "https://github.com/tesseract-ocr/tessdata_fast/raw/main/dan.traineddata" `
          -OutFile "$tessdata\dan.traineddata"

      - name: Install PyInstaller
        run: uv pip install pyinstaller

      - name: Check PyInstaller version
        run: uv run pyinstaller --version

      - name: Build Windows executable
        run: >
          uv run pyinstaller
          --name CALDISS_Anonymiserings_program
          --onedir
          --windowed
          --python-option "X utf8=1"
          --paths .
          --collect-submodules Shared_Functions
          --collect-submodules Pipelines.Frontend
          --collect-submodules Pipelines.Backend
          --collect-data ocrmypdf
          --collect-submodules ocrmypdf.builtin_plugins
          main.py

      - name: Bundle Tesseract
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force `
            "dist/CALDISS_Anonymiserings_program/tools/tesseract"

          Copy-Item `
            "C:/Program Files/Tesseract-OCR/*" `
            "dist/CALDISS_Anonymiserings_program/tools/tesseract/" `
            -Recurse

      - name: Test application imports
        run: uv run python -c "import main; print('Application imported successfully')"

      - name: Upload Windows executable
        uses: actions/upload-artifact@v6
        with:
          name: CALDISS_Anonymiserings_program-Windows
          path: dist/CALDISS_Anonymiserings_program/